name: Give Strava Kudos

on: [push]



jobs:
    runs-on: ubuntu-latest
    env:
      STRAVA_EMAIL: ${{ secrets.MY_STRAVA_EMAIL }}
      STRAVA_PASSWORD: ${{ secrets.MY_STRAVA_PASSWORD }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '>=3.9.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: playwright install

      - run: echo "checking if variable is set $STRAVA_PASSWORD"
      - run: python give_kudos.py
        

